Update cicd_github.yml

diff --git a/.github/workflows/cicd_github.yml b/.github/workflows/cicd_github.yml
--- a/.github/workflows/cicd_github.yml
+++ b/.github/workflows/cicd_github.yml
@@ -19,7 +19,7 @@ jobs:
 
     - name: Install dependencies
       run: |
-        sudo apt-get install -y build-essential cmake git libcurl4-openssl-dev
+        sudo apt-get install -y build-essential git libcurl4-openssl-dev libcurl4 zlib1g-dev pkg-config
 
     - name: Install Prometheus C++ Client
       run: |
@@ -32,6 +32,10 @@ jobs:
         cmake .. -DBUILD_SHARED_LIBS=ON
         make
         sudo make install
+
+    - name: Verify Prometheus C++ Client installation
+      run: |
+        pkg-config --exists prometheus-cpp || (echo "Prometheus C++ Client not found!"; exit 1)
     
     - name: build
       run: cd ./src && make build
